---
galaxy_info:
  role_name: cron
  author: Ricky Dua
  description: Installs cron jobs on root user

  license: license (BSD, MIT)

  platforms:
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - focal
        - bionic

  min_ansible_version: "2.1"

  galaxy_tags: []

dependencies: []
