---
- hosts: chicken
  become: true
  vars_files:
    - vars/secrets.yml

  pre_tasks:
    - name: Check user is root
      assert:
        that:
          - ansible_user_id == "root"

    - name: Load vars based on OS type
      include_vars: "vars/unattended_upgrades_{{ ansible_distribution | lower }}.yml"

    - name: Update apt cache and upgrade
      apt:
        update_cache: true
        upgrade: true

  roles:
    - role: nfs
    - role: iscsi
    - role: docker
    - role: jnv.unattended-upgrades
    - role: cron

  tasks:
    - name: "Install misc packages"
      apt:
        name:
          - htop
          - qemu-guest-agent
