---
- hosts: chicken
  become: true
  vars_files:
    - vars/secrets.yml

  pre_tasks:
    - name: Check user is root
      assert:
        that:
          - ansible_user_id == "root"

    - include_tasks: tasks/nginx_assert.yml

    - name: Update apt cache and upgrade
      apt:
        update_cache: true
        upgrade: true

  roles:
    - role: nfs
    - role: docker
    - role: geerlingguy.certbot
    - role: geerlingguy.nginx
    - role: jnv.unattended-upgrades
    - role: cron

  tasks:
    - name: "Install misc packages"
      apt:
        name:
          - htop
          - qemu-guest-agent
