---
# https://taskfile.dev
version: "3"

tasks:
  bootstrap:
    cmds:
      - pip3 install -r ./requirements.txt
      - ansible-galaxy install --roles-path ./roles -r requirements.yml
      - ansible-galaxy collection install -r requirements.yml
    silent: true

  lint:
    cmds:
      - find . \( -name "*.yml" -o -name "*.yaml" \) -a -exec yamllint "{}" +;
      - ansible-lint eggs.yml site.yml
      - cd scripts && shellcheck *.sh
      - black --check scripts/*.py
