---
galaxy_info:
  author: Ricky Dua
  description: >-
    Install iSCSI initiator client, discover targets on target machine,
    login to it and mount it

  license: license (BSD, MIT)

  platforms:
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - focal
        - bionic

  min_ansible_version: "2.1"

  galaxy_tags: []

dependencies: []
