---
galaxy_info:
  author: Ricky Dua
  description: Install nfs package and mount nfs share

  license: license (BSD, MIT)

  platforms:
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - focal
        - bionic

  min_ansible_version: 2.1

  galaxy_tags: []

dependencies: []
