---
argument_specs:
  main:
    short_description: Required args for this role
    options:
      influxdb_pass:
        type: str
        required: true

      pihole_pass:
        type: str
        required: true

      nfs_mountpoint:
        type: str
        required: true

      iscsi_config_directory:
        type: str
        required: true
